### ISSUE TITLE
implement starknet support

### ISSUE THREAD

**Issue by nionis** [hoprnet/RPCh#392]
### Description

In our [Argent X extension](https://github.com/Rpc-h/extension-argent-x) fork, we were able to send transactions to starknet.
However, we haven't been able to _read_ data.
This is because starknet endpoints require a specific set of `headers` that our exit-nodes do not forward.

### Relevant issues

- [x] SDK: add optional starknet support (and the ability to send non-evm-rpc bodies, which can be generalized for supporting more L2s)
- [x] SDK: requests must be marked as starknet requests
- [x] exit-node: forward required headers to the starknet provider
- [x] https://github.com/hoprnet/hopr-bounty-submission/issues/9

### Definition of DONE

Once the RPCh ecosystem can support starknet requests and our Argent X fork has been updated to support reading data.

**Comment by esterlus** [comment]
RPCh works with starknet
